"""Small shared helpers: time handling, truncation, redaction, ticket detection."""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import re
from typing import Any, Iterable, List, Optional, Set

# --------------------------------------------------------------------------- time

def local_tz() -> dt.tzinfo:
    """The machine's local timezone (used for sprint day boundaries)."""
    tz = dt.datetime.now().astimezone().tzinfo
    return tz or dt.timezone.utc


def parse_date(s: str) -> dt.date:
    """Strict YYYY-MM-DD parsing. Raises ValueError with a friendly message."""
    try:
        return dt.date.fromisoformat(s.strip())
    except ValueError:
        raise ValueError(f"invalid date {s!r}; expected YYYY-MM-DD") from None


def day_start(d: dt.date, tz: dt.tzinfo) -> dt.datetime:
    return dt.datetime(d.year, d.month, d.day, tzinfo=tz)


def day_end_exclusive(d: dt.date, tz: dt.tzinfo) -> dt.datetime:
    return day_start(d, tz) + dt.timedelta(days=1)


def parse_ts(value: Any) -> Optional[dt.datetime]:
    """Parse the timestamps found in Claude Code JSONL (ISO-8601 with Z) or epoch ms."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        # epoch milliseconds (history.jsonl / desktop metadata) or seconds
        secs = value / 1000.0 if value > 1e11 else float(value)
        try:
            return dt.datetime.fromtimestamp(secs, tz=dt.timezone.utc)
        except (OverflowError, OSError, ValueError):
            return None
    if isinstance(value, str):
        s = value.strip()
        if s.endswith("Z"):
            s = s[:-1] + "+00:00"
        try:
            t = dt.datetime.fromisoformat(s)
        except ValueError:
            return None
        if t.tzinfo is None:
            t = t.replace(tzinfo=dt.timezone.utc)
        return t
    return None


def fmt_local(t: Optional[dt.datetime], tz: dt.tzinfo, with_date: bool = True) -> str:
    if not t:
        return "?"
    lt = t.astimezone(tz)
    return lt.strftime("%Y-%m-%d %H:%M") if with_date else lt.strftime("%H:%M")


def human_minutes(minutes: float) -> str:
    minutes = int(round(minutes))
    if minutes < 60:
        return f"{minutes} min"
    h, m = divmod(minutes, 60)
    return f"{h}h {m:02d}m"


# ---------------------------------------------------------------------- text

def truncate(text: str, head: int, tail: int = 0) -> str:
    """Keep the first `head` and last `tail` chars with an explicit marker in between."""
    if text is None:
        return ""
    if len(text) <= head + tail + 40:
        return text
    cut = len(text) - head - tail
    marker = f"\n… [{cut:,} chars truncated] …\n"
    return text[:head].rstrip() + marker + (text[-tail:].lstrip() if tail else "")


_TAG_BLOCKS = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S),
    re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.S),
    re.compile(r"<local-command-caveat>.*?</local-command-caveat>", re.S),
    re.compile(r"<ide_opened_file>.*?</ide_opened_file>", re.S),
    re.compile(r"<ide_selection>.*?</ide_selection>", re.S),
    re.compile(r"<task-notification>.*?</task-notification>", re.S),
    re.compile(r"<ci-monitor-event>.*?</ci-monitor-event>", re.S),
]
_CMD_NAME = re.compile(r"<command-name>(.*?)</command-name>", re.S)
_CMD_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S)
_CMD_MSG = re.compile(r"<command-message>.*?</command-message>", re.S)
_ANY_TAG_LINE = re.compile(r"^\s*<[a-z_\-]+(?:\s[^>]*)?>\s*$", re.M)

NOISE_PREFIXES = (
    "[Request interrupted by user",
    "Warmup",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
)


def clean_user_text(text: str) -> str:
    """Strip harness-injected markup from a user turn; return '' if nothing human remains."""
    if not text:
        return ""
    # Slash commands: turn <command-name>/foo</command-name><command-args>x</command-args> into "/foo x"
    name = _CMD_NAME.search(text)
    if name:
        args = _CMD_ARGS.search(text)
        cmd = name.group(1).strip()
        if args and args.group(1).strip():
            cmd += " " + args.group(1).strip()
        text = _CMD_MSG.sub("", text)
        text = _CMD_NAME.sub("", text)
        text = _CMD_ARGS.sub("", text)
        text = (cmd + "\n" + text).strip()
    for rx in _TAG_BLOCKS:
        text = rx.sub("", text)
    text = _ANY_TAG_LINE.sub("", text)
    text = text.strip()
    if not text:
        return ""
    for p in NOISE_PREFIXES:
        if text.startswith(p):
            return ""
    return text


# ----------------------------------------------------------------- redaction
# Session transcripts can contain pasted secrets. Everything sent to the model is
# redacted first (OWASP A02 / A09: never leak credentials into logs or prompts).

SECRET_PATTERNS = [
    (re.compile(r"sk-ant-[A-Za-z0-9_\-]{8,}"), "[REDACTED_KEY]"),
    (re.compile(r"\bsk-[A-Za-z0-9_\-]{16,}"), "[REDACTED_KEY]"),
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"), "[REDACTED_TOKEN]"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "[REDACTED_AWS_KEY]"),
    (re.compile(r"\bxox[baprs]-[A-Za-z0-9\-]{10,}"), "[REDACTED_SLACK_TOKEN]"),
    (re.compile(r"\beyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}"), "[REDACTED_JWT]"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----"), "[REDACTED_PRIVATE_KEY]"),
    (re.compile(r"(?i)\b(bearer)\s+[A-Za-z0-9._\-]{16,}"), r"\1 [REDACTED]"),
    (re.compile(r"(?i)\b(password|passwd|pwd|secret|api[_\-]?key|access[_\-]?token|auth[_\-]?token|"
                r"client[_\-]?secret|private[_\-]?key|refresh[_\-]?token)\b(\s*[=:]\s*)[\"']?[^\s\"',;]{6,}"),
     r"\1\2[REDACTED]"),
    (re.compile(r"(?i)(https?://[^\s/@:]+:)[^\s@/]{4,}(@)"), r"\1[REDACTED]\2"),
]


def redact(text: str) -> str:
    if not text:
        return text
    for rx, repl in SECRET_PATTERNS:
        text = rx.sub(repl, text)
    return text


# -------------------------------------------------------------------- tickets

TICKET_RE = re.compile(r"\b([A-Z][A-Z0-9]{1,9})-(\d{2,7})\b")
# Prefixes that look like tickets but are not (hash names, standards, encodings...).
TICKET_DENY: Set[str] = {
    "SHA", "UTF", "ISO", "RSA", "AES", "ECC", "CVE", "TLS", "HTTP", "HTTPS", "IPV", "MD", "HMAC",
    "RFC", "IEEE", "ECMA", "PBKDF", "ARGON", "X", "ES", "V", "ID", "UUID", "ERR", "ERROR", "PORT",
    "EXIT", "CODE", "STATUS", "GPT", "GMT", "UTC", "IST", "PST", "EST", "WIN", "X64", "ARM", "ARM64",
    "MACOS", "OS", "E", "T", "U", "P", "S", "FIPS", "PCI", "SOC", "GDPR", "ERRNO", "SIG", "REQ", "MSG",
}


def find_tickets(*texts: Optional[str]) -> List[str]:
    """Return ticket ids (e.g. FIX-133803) found in the given texts, first-seen order."""
    seen: List[str] = []
    for t in texts:
        if not t:
            continue
        for m in TICKET_RE.finditer(t):
            prefix, num = m.group(1), m.group(2)
            if prefix in TICKET_DENY:
                continue
            # Hostnames like CORP-LAP-1269: an UPPERCASE token glued on with '-' means it is
            # one identifier, not a ticket. (Branch names use lowercase before the ticket.)
            before = t[max(0, m.start() - 12):m.start()]
            if re.search(r"[A-Z]{2,}-$", before):
                continue
            tid = f"{prefix}-{num}"
            if tid not in seen:
                seen.append(tid)
    return seen


# ----------------------------------------------------------------------- misc

def stable_hash(*parts: Any) -> str:
    h = hashlib.sha256()
    for p in parts:
        h.update(json.dumps(p, sort_keys=True, default=str).encode("utf-8"))
        h.update(b"\x00")
    return h.hexdigest()[:16]


def uniq(items: Iterable[str]) -> List[str]:
    out: List[str] = []
    seen: Set[str] = set()
    for i in items:
        if i and i not in seen:
            seen.add(i)
            out.append(i)
    return out


def short_project(cwd: str) -> str:
    """'/Users/x/develop/local-setup/git/acme/acme-web' -> 'acme/acme-web'."""
    if not cwd:
        return "?"
    parts = [p for p in cwd.split("/") if p]
    if ".claude" in parts and "worktrees" in parts:
        i = parts.index("worktrees")
        base = parts[i - 2] if i >= 2 else "?"
        return f"{base} (worktree {parts[-1]})"
    return "/".join(parts[-2:]) if len(parts) >= 2 else cwd
